version: '3.7'
services:
  fastapi:
    build: './fastapi'
    ports:
      - "80:80"
    volumes:
      - "./fastapi/app/:/app"
      - /app/__pycache__/
    environment:
      - GUNICORN_CMD_ARGS="--reload"
    depends_on:
      - "servingtf"
  servingtf:
    build: './servingtf'
    ports:
      - "8501:8501"
