version: '3.7'
services:
  fastapi:
    build: './fastapi'
    ports:
      - "80:80"
    volumes:
      - "./fastapi/app/:/app/app"
      - /app/__pycache__/
    entrypoint: ['/start-reload.sh']
    environment:
      - MY_MODEL_NAME=classify_chat_text
    depends_on:
      - "servingtf"
  servingtf:
    build:
      context: './servingtf'
      args:
        MY_MODEL_NAME: classify_chat_text
